// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/RomanUtolin/RESTful-CRUD/internall/entity"
	mock "github.com/stretchr/testify/mock"
)

// PersonLogic is an autogenerated mock type for the PersonLogic type
type PersonLogic struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *PersonLogic) Create(ctx context.Context, req *entity.Person) (*entity.Person, error) {
	ret := _m.Called(ctx, req)

	var r0 *entity.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Person) (*entity.Person, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Person) *entity.Person); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Person) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PersonLogic) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *PersonLogic) GetAll(ctx context.Context) ([]*entity.Person, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Person, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Person); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *PersonLogic) GetByEmail(ctx context.Context, email string) (*entity.Person, error) {
	ret := _m.Called(ctx, email)

	var r0 *entity.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Person, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Person); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PersonLogic) GetByID(ctx context.Context, id int) (*entity.Person, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entity.Person, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Person); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *PersonLogic) Update(ctx context.Context, id int, req *entity.Person) (*entity.Person, error) {
	ret := _m.Called(ctx, id, req)

	var r0 *entity.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *entity.Person) (*entity.Person, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *entity.Person) *entity.Person); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *entity.Person) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonLogic creates a new instance of PersonLogic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonLogic(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonLogic {
	mock := &PersonLogic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
